### ISSUE TITLE
How is this different from async?

### ISSUE THREAD

**Issue by diegoaguilar** [IonicaBizau/same-time#1]
I find this very similar to async's parallel functions, how does same-time make an alternative?

**Comment by IonicaBizau** [comment]
It is about 24x smaller than `async`. :smile: 
I was never a fan of big libraries like `underscore`, `async` etc. You sacrifice performance for convenience.

I won't do that. :smile_cat: I like little libraries doing one thing at the time and do it good. :four_leaf_clover:
